=== guszhang/guszhang.github.io/IPTVisual/mvField3DP3.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://peu.cloud/schema/mv/mvField3DP3.schema.json",
    "title": "mvField3DP3",
    "description": "MagVisual 3D Field Array with 3D vectors",
    "type": "object",
    "properties": {
        "uid": {
            "description": "unique id of the 3D array",
            "type": "string"
        },
        "tag": {
            "description": "data tag",
            "type": "string"
        },
        "origin":{
            "description": "data origin",
            "type": "array",
            "items": {
                "$ref": "./mvPoint3.schema.json"
            },
            "minItems": 1
        },
        "vector": {
            "description": "data vector",
            "type": "array",
            "items":{
                "$ref": "./mvPoint3.schema.json"
            },
            "minItems": 1
        },
        "color":{
            "description": "color for display",
            "type": "string"
        }
    },
    "required": [
        "uid","tag","origin","vector"
    ]
}

=== guszhang/guszhang.github.io/IPTVisual/Case1.fieldTA.dat.json
{"$schema":"./mvField3DP3.schema.json","uid":"8ea9a141500fa658a0d61da5bb00ee3ebc96748e","tag":"PoyntingVector","origin":[[-0.225,-0.125,-0.175],[-0.225,-0.125,-0.125],[-0.225,-0.125,-0.07499999999999998],[-0.225,-0.125,-0.024999999999999994],[-0.225,-0.125,0.025000000000000022],[-0.225,-0.125,0.07500000000000001],[-0.225,-0.125,0.125],[-0.225,-0.125,0.17500000000000004],[-0.225,-0.07499999999999998,-0.225],[-0.225,-0.07499999999999998,-0.175],[-0.225,-0.07499999999999998,-0.125],[-0.225,-0.07499999999999998,-0.07499999999999998],[-0.225,-0.07499999999999998,-0.024999999999999994],[-0.225,-0.07499999999999998,0.025000000000000022],[-0.225,-0.07499999999999998,0.07500000000000001],[-0.225,-0.07499999999999998,0.125],[-0.225,-0.07499999999999998,0.17500000000000004],[-0.225,-0.07499999999999998,0.22500000000000003],[-0.225,-0.024999999999999994,-0.225],[-0.225,-0.024999999999999994,-0.175],[-0.225,-0.024999999999999994,-0.125],[-0.225,-0.024999999999999994,-0.07499999999999998],[-0.225,-0.024999999999999994,-0.024999999999999994],[-0.225,-0.024999999999999994,0.025000000000000022],[-0.225,-0.024999999999999994,0.07500000000000001],[-0.225,-0.024999999999999994,0.125],[-0.225,-0.024999999999999994,0.17500000000000004],[-0.225,-0.024999999999999994,0.22500000000000003],[-0.225,0.025000000000000022,-0.225],[-0.225,0.025000000000000022,-0.175],[-0.225,0.025000000000000022,-0.125],[-0.225,0.025000000000000022,-0.07499999999999998],[-0.225,0.025000000000000022,-0.024999999999999994],[-0.225,0.025000000000000022,0.025000000000000022],[-0.225,0.025000000000000022,0.07500000000000001],[-0.225,0.025000000000000022,0.125],[-0.225,0.025000000000000022,0.17500000000000004],[-0.225,0.025000000000000022,0.22500000000000003],[-0.225,0.07500000000000001,-0.225],[-0.225,0.07500000000000001,-0.175],[-0.225,0.07500000000000001,-0.125],[-0.225,0.07500000000000001,-0.07499999999999998],[-0.225,0.07500000000000001,-0.024999999999999994],[-0.225,0.07500000000000001,0.025000000000000022],[-0.225,0.07500000000000001,0.07500000000000001],[-0.225,0.07500000000000001,0.125],[-0.225,0.07500000000000001,0.17500000000000004],[-0.225,0.07500000000000001,0.22500000000000003],[-0.225,0.12500000000000003,-0.225],[-0.225,0.12500000000000003,-0.175],[-0.225,0.12500000000000003,-0.125],[-0.225,0.12500000000000003,-0.07499999999999998],[-0.225,0.12500000000000003,-0.024999999999999994],[-0.225,0.12500000000000003,0.025000000000000022],[-0.225,0.12500000000000003,0.07500000000000001],[-0.225,0.12500000000000003,0.125],[-0.225,0.12500000000000003,0.17500000000000004],[-0.225,0.12500000000000003,0.22500000000000003],[-0.225,0.17500000000000002,-0.225],[-0.225,0.17500000000000002,-0.175],[-0.225,0.17500000000000002,-0.125],[-0.225,0.17500000000000002,-0.07499999999999998],[-0.225,0.17500000000000002,-0.024999999999999994],[-0.225,0.17500000000000002,0.025000000000000022],[-0.225,0.17500000000000002,0.07500000000000001],[-0.225,0.17500000000000002,0.125],[-0.225,0.17500000000000002,0.17500000000000004],[-0.225,0.17500000000000002,0.22500000000000003],[-0.225,0.225,-0.225],[-0.225,0.225,-0.175],[-0.225,0.225,-0.125],[-0.225,0.225,-0.07499999999999998],[-0.225,0.225,-0.024999999999999994],[-0.225,0.225,0.025000000000000022],[-0.225,0.225,0.07500000000000001],[-0.225,0.225,0.125],[-0.225,0.225,0.17500000000000004],[-0.225,0.225,0.22500000000000003],[-0.225,0.275,-0.225],[-0.225,0.275,-0.175],[-0.225,0.275,-0.125],[-0.225,0.275,-0.07499999999999998],[-0.225,0.275,-0.024999999999999994],[-0.225,0.275,0.025000000000000022],[-0.225,0.275,0.07500000000000001],[-0.225,0.275,0.125],[-0.225,0.275,0.17500000000000004],[-0.225,0.275,0.22500000000000003],[-0.225,0.32500000000000007,-0.175],[-0.225,0.32500000000000007,-0.125],[-0.225,0.32500000000000007,-0.07499999999999998],[-0.225,0.32500000000000007,-0.024999999999999994],[-0.225,0.32500000000000007,0.025000000000000022],[-0.225,0.32500000000000007,0.07500000000000001],[-0.225,0.32500000000000007,0.125],[-0.225,0.32500000000000007,0.17500000000000004],[-0.175,-0.125,-0.225],[-0.175,-0.125,-0.175],[-0.175,-0.125,-0.125],[-0.175,-0.125,-0.07499999999999998],[-0.175,-0.125,-0.024999999999999994],[-0.175,-0.125,0.025000000000000022],[-0.175,-0.125,0.07500000000000001],[-0.175,-0.125,0.125],[-0.175,-0.125,0.17500000000000004],[-0.175,-0.125,0.22500000000000003],[-0.175,-0.07499999999999998,-0.225],[-0.175,-0.07499999999999998,-0.175],[-0.175,-0.07499999999999998,-0.125],[-0.175,-0.07499999999999998,-0.07499999999999998],[-0.175,-0.07499999999999998,-0.024999999999999994],[-0.175,-0.07499999999999998,0.025000000000000022],[-0.175,-0.07499999999999998,0.07500000000000001],[-0.175,-0.07499999999999998,0.125],[-0.175,-0.07499999999999998,0.17500000000000004],[-0.175,-0.07499999999999998,0.22500000000000003],[-0.175,-0.024999999999999994,-0.225],[-0.175,-0.024999999999999994,-0.175],[-0.175,-0.024999999999999994,-0.125],[-0.175,-0.024999999999999994,-0.07499999999999998],[-0.175,-0.024999999999999994,-0.024999999999999994],[-0.175,-0.024999999999999994,0.025000000000000022],[-0.175,-0.024999999999999994,0.07500000000000001],[-0.175,-0.024999999999999994,0.125],[-0.175,-0.024999999999999994,0.17500000000000004],[-0.175,-0.024999999999999994,0.22500000000000003],[-0.175,0.025000000000000022,-0.225],[-0.175,0.025000000000000022,-0.175],[-0.175,0.025000000000000022,-0.125],[-0.175,0.025000000000000022,-0.07499999999999998],[-0.175,0.025000000000000022,-0.024999999999999994],[-0.175,0.025000000000000022,0.025000000000000022],[-0.175,0.025000000000000022,0.07500000000000001],[-0.175,0.025000000000000022,0.125],[-0.175,0.025000000000000022,0.17500000000000004],[-0.175,0.025000000000000022,0.22500000000000003],[-0.175,0.07500000000000001,-0.225],[-0.175,0.07500000000000001,-0.175],[-0.175,0.07500000000000001,-0.125],[-0.175,0.07500000000000001,-0.07499999999999998],[-0.175,0.07500000000000001,-0.024999999999999994],[-0.175,0.07500000000000001,0.025000000000000022],[-0.175,0.07500000000000001,0.07500000000000001],[-0.175,0.07500000000000001,0.125],[-0.175,0.07500000000000001,0.17500000000000004],[-0.175,0.07500000000000001,0.22500000000000003],[-0.175,0.12500000000000003,-0.225],[-0.175,0.12500000000000003,-0.175],[-0.175,0.12500000000000003,-0.125],[-0.175,0.12500000000000003,-0.07499999999999998],[-0.175,0.12500000000000003,-0.024999999999999994],[-0.175,0.12500000000000003,0.025000000000000022],[-0.175,0.12500000000000003,0.07500000000000001],[-0.175,0.12500000000000003,0.125],[-0.175,0.12500000000000003,0.17500000000000004],[-0.175,0.12500000000000003,0.22500000000000003],[-0.175,0.17500000000000002,-0.225],[-0.175,0.17500000000000002,-0.175],[-0.175,0.17500000000000002,-0.125],[-0.175,0.17500000000000002,-0.07499999999999998],[-0.175,0.17500000000000002,-0.024999999999999994],[-0.175,0.17500000000000002,0.025000000000000022],[-0.175,0.17500000000000002,0.07500000000000001],[-0.175,0.17500000000000002,0.125],[-0.175,0.17500000000000002,0.17500000000000004],[-0.175,0.17500000000000002,0.22500000000000003],[-0.175,0.225,-0.225],[-0.175,0.225,-0.175],[-0.175,0.225,-0.125],[-0.175,0.225,-0.07499999999999998],[-0.175,0.225,-0.024999999999999994],[-0.175,0.225,0.025000000000000022],[-0.175,0.225,0.07500000000000001],[-0.175,0.225,0.125],[-0.175,0.225,0.17500000000000004],[-0.175,0.225,0.22500000000000003],[-0.175,0.275,-0.225],[-0.175,0.275,-0.175],[-0.175,0.275,-0.125],[-0.175,0.275,-0.07499999999999998],[-0.175,0.275,-0.024999999999999994],[-0.175,0.275,0.025000000000000022],[-0.175,0.275,0.07500000000000001],[-0.175,0.275,0.125],[-0.175,0.275,0.17500000000000004],[-0.175,0.275,0.22500000000000003],[-0.175,0.32500000000000007,-0.225],[-0.175,0.32500000000000007,-0.175],[-0.175,0.32500000000000007,-0.125],[-0.175,0.32500000000000007,-0.07499999999999998],[-0.175,0.32500000000000007,-0.024999999999999994],[-0.175,0.32500000000000007,0.025000000000000022],[-0.175,0.32500000000000007,0.07500000000000001],[-0.175,0.32500000000000007,0.125],[-0.175,0.32500000000000007,0.17500000000000004],[-0.175,0.32500000000000007,0.22500000000000003],[-0.125,-0.125,-0.225],[-0.125,-0.125,-0.175],[-0.125,-0.125,-0.125],[-0.125,-0.125,-0.07499999999999998],[-0.125,-0.125,-0.024999999999999994],[-0.125,-0.125,0.025000000000000022],[-0.125,-0.125,0.07500000000000001],[-0.125,-0.125,0.125],[-0.125,-0.125,0.17500000000000004],[-0.125,-0.125,0.22500000000000003],[-0.125,-0.07499999999999998,-0.225],[-0.125,-0.07499999999999998,-0.175],[-0.125,-0.07499999999999998,-0.125],[-0.125,-0.07499999999999998,-0.07499999999999998],[-0.125,-0.07499999999999998,-0.024999999999999994],[-0.125,-0.07499999999999998,0.025000000000000022],[-0.125,-0.07499999999999998,0.07500000000000001],[-0.125,-0.07499999999999998,0.125],[-0.125,-0.07499999999999998,0.17500000000000004],[-0.125,-0.07499999999999998,0.22500000000000003],[-0.125,-0.024999999999999994,-0.225],[-0.125,-0.024999999999999994,-0.175],[-0.125,-0.024999999999999994,-0.125],[-0.125,-0.024999999999999994,-0.07499999999999998],[-0.125,-0.024999999999999994,-0.024999999999999994],[-0.125,-0.024999999999999994,0.025000000000000022],[-0.125,-0.024999999999999994,0.07500000000000001],[-0.125,-0.024999999999999994,0.125],[-0.125,-0.024999999999999994,0.17500000000000004],[-0.125,-0.024999999999999994,0.22500000000000003],[-0.125,0.025000000000000022,-0.225],[-0.125,0.025000000000000022,-0.175],[-0.125,0.025000000000000022,-0.125],[-0.125,0.025000000000000022,-0.07499999999999998],[-0.125,0.025000000000000022,-0.024999999999999994],[-0.125,0.025000000000000022,0.025000000000000022],[-0.125,0.025000000000000022,0.07500000000000001],[-0.125,0.025000000000000022,0.125],[-0.125,0.025000000000000022,0.17500000000000004],[-0.125,0.025000000000000022,0.22500000000000003],[-0.125,0.07500000000000001,-0.225],[-0.125,0.07500000000000001,-0.175],[-0.125,0.07500000000000001,-0.125],[-0.125,0.07500000000000001,-0.07499999999999998],[-0.125,0.07500000000000001,-0.024999999999999994],[-0.125,0.07500000000000001,0.025000000000000022],[-0.125,0.
