=== guszhang/guszhang.github.io/IPTVisual/mv2/schema/mvRoundWinding1DP3.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://peu.cloud/mv2/schema/mvRoundWinding1DP3.schema.json",
    "title": "mvArr1D",
    "description": "MagVisual round cross-section wingding object 1-Dimensional with 3D coordinates",
    "type": "object",
    "properties": {
        "uid": {
            "description": "unique id of the 1D array",
            "type": "string"
        },
        "tag": {
            "description": "data tag",
            "type": "string"
        },
        "data": {
            "description": "data storage",
            "type": "array",
            "items":{
                "$ref": "./mvPoint3.schema.json"
            },
            "minItems": 1
        },
        "cs_radius":{
            "description": "cross section radius",
            "type": "number"
        },
        "color":{
            "description": "color for display",
            "type": "string"
        }
    },
    "required": [
        "uid","tag","data","cs_radius"
    ]
}

=== guszhang/guszhang.github.io/IPTVisual/Samples/TwoCoilResonance/disp/c1.json
{"$schema":"http://peu.cloud/mv2/schema/mvRoundWinding1DP3.schema.json","color":"#FF00FF","cs_radius":0.00075,"data":[[0.15,1,0],[0.1499924924524794,1.0000031369426752,-0.0015007357838434936],[0.14996997056142788,1.0000062738853503,-0.003001321343084146],[0.149932436581301,1.0000094108280255,-0.004501606468156695],[0.14987989426927398,1.0000125477707007,-0.006001440979569528],[0.14981234888486547,1.0000156847133759,-0.007500674742937746],[0.14972980718941134,1.000018821656051,-0.008999157684011707],[0.14963227744538754,1.0000219585987262,-0.010496739803699565],[0.14951976941558323,1.0000250955414012,-0.011993271193082251],[0.14939229436212356,1.0000282324840764,-0.01348860204841948],[0.14924986504534207,1.0000313694267515,-0.014982582686145177],[0.14909249572250366,1.0000345063694267,-0.016475063557850906],[0.14892020214637725,1.0000376433121019,-0.017965895265255764],[0.14873300156365893,1.000040780254777,-0.019454928575161238],[0.14853091271324573,1.0000439171974522,-0.020942014434389547],[0.14831395582435952,1.0000470541401274,-0.022427003984703937],[0.14808215261452243,1.0000501910828026,-0.023909748577709534],[0.1478355262873826,1.0000533280254778,-0.025390099789733098],[0.14757410153039166,1.000056464968153,-0.026867909436680344],[0.14729790451233338,1.000059601910828,-0.028343029588869254],[0.1470069628807043,1.0000627388535033,-0.02981531258583795],[0.1467013057589461,1.0000658757961784,-0.03128461105112559],[0.1463809637435303,1.0000690127388534,-0.03275077790702483],[0.14604596890089563,1.0000721496815286,-0.034213666389304426],[0.14569635476423812,1.0000752866242038,-0.035673130061900406],[0.14533215633015437,1.000078423566879,-0.037129022831574404],[0.14495341005513832,1.000081560509554,-0.03858119896253772],[0.14456015385193213,1.0000846974522293,-0.040029513091039554],[0.14415242708573092,1.0000878343949045,-0.04147382023991794],[0.14373027057024232,1.0000909713375796,-0.04291397583311217],[0.14329372656360098,1.0000941082802548,-0.04434983571013487],[0.14284283876413859,1.00009724522293,-0.04578125614050258],[0.14237765230600954,1.0001003821656052,-0.047208093838123265],[0.14189821375467307,1.0001035191082803,-0.048630205975639315],[0.14140457110223192,1.0001066560509555,-0.05004745019872474],[0.14089677376262838,1.0001097929936307,-0.051459684640334805],[0.14037487256669792,1.0001129299363056,-0.0528667679349071],[0.13983891975708088,1.0001160668789808,-0.054268559232512316],[0.1392889689829931,1.000119203821656,-0.05566491821295338],[0.13872507529485553,1.0001223407643312,-0.05705570509981158],[0.13814729513878363,1.0001254777070063,-0.05844078067443834],[0.13755568635093712,1.0001286146496815,-0.05982000628989105],[0.13695030815173054,1.0001317515923567,-0.06119324388481172],[0.13633122113990515,1.0001348885350319,-0.06256035599724699],[0.1356984872864631,1.000138025477707,-0.06392120577840821],[0.13505216992846408,1.0001411624203822,-0.06527565700637002],[0.13439233376268506,1.0001442993630574,-0.0666235740997063],[0.13371904483914437,1.0001474363057326,-0.067964822131062],[0.13303237055448983,1.0001505732484077,-0.06929926684065933],[0.13233237964525243,1.000153710191083,-0.07062677464973735],[0.13161914218096568,1.000156847133758,-0.07194721267392323],[0.1308927295571517,1.000159984076433,-0.07326044873653413],[0.13015321448817435,1.0001631210191082,-0.07456635138180812],[0.12940067099996067,1.0001662579617834,-0.07586478988806293],[0.12863517442259056,1.0001693949044586,-0.07715563428078145],[0.1278568013827565,1.0001725318471337,-0.07843875534562204],[0.12706562979609295,1.000175668789809,-0.07971402464135309],[0.12626173885937705,1.000178805732484,-0.08098131451271012],[0.12544520904260087,1.0001819426751593,-0.08224049810317402],[0.12461612208091642,1.0001850796178344,-0.08349144936766957],[0.12377456096645394,1.0001882165605096,-0.08473404308518258],[0.12292060994001416,1.0001913535031848,-0.08596815487129458],[0.12205435448263594,1.00019449044586,-0.08719366119063386],[0.12117588130703937,1.0001976273885351,-0.08841043936924138],[0.12028527834894598,1.0002007643312103,-0.08961836760685046],[0.11938263475827615,1.0002039012738853,-0.09081732498907921],[0.11846804089022525,1.0002070382165604,-0.09200719149953399],[0.11754158829621894,1.0002101751592356,-0.09318784803182316],[0.1166033697147489,1.0002133121019108,-0.09435917640147978],[0.11565347906208959,1.000216449044586,-0.09552105935779191],[0.1146920114228972,1.0002195859872611,-0.09667338059553941],[0.11371906304069163,1.0002227229299363,-0.09781602476663628],[0.11273473130822237,1.0002258598726115,-0.09894887749167701],[0.11173911475771955,1.0002289968152867,-0.10007182537138602],[0.11073231305103069,1.0002321337579618,-0.10118475599796907],[0.10971442696964454,1.000235270700637,-0.10228755796636527],[0.10868555840460281,1.0002384076433122,-0.10338012088539879],[0.10764581034630076,1.0002415445859874,-0.10446233538882925],[0.1065952868741778,1.0002446815286625,-0.10553409314629912],[0.10553409314629912,1.0002478184713375,-0.1065952868741778],[0.10446233538882924,1.0002509554140127,-0.10764581034630076],[0.10338012088539879,1.0002540923566878,-0.10868555840460283],[0.10228755796636525,1.000257229299363,-0.10971442696964455],[0.10118475599796908,1.0002603662420382,-0.11073231305103069],[0.10007182537138602,1.0002635031847134,-0.11173911475771954],[0.09894887749167701,1.0002666401273885,-0.11273473130822237],[0.0978160247666363,1.0002697770700637,-0.11371906304069163],[0.09667338059553941,1.0002729140127389,-0.1146920114228972],[0.09552105935779191,1.000276050955414,-0.11565347906208959],[0.0943591764014798,1.0002791878980892,-0.11660336971474888],[0.09318784803182317,1.0002823248407644,-0.11754158829621894],[0.09200719149953399,1.0002854617834396,-0.11846804089022522],[0.09081732498907923,1.0002885987261148,-0.11938263475827614],[0.08961836760685048,1.0002917356687897,-0.12028527834894598],[0.0884104393692414,1.0002948726114649,-0.12117588130703935],[0.08719366119063386,1.00029800955414,-0.12205435448263591],[0.08596815487129458,1.0003011464968152,-0.12292060994001416],[0.08473404308518255,1.0003042834394904,-0.12377456096645394],[0.08349144936766956,1.0003074203821656,-0.12461612208091642],[0.08224049810317402,1.0003105573248408,-0.12544520904260087],[0.08098131451271014,1.000313694267516,-0.12626173885937703],[0.07971402464135309,1.000316831210191,-0.12706562979609295],[0.07843875534562204,1.0003199681528663,-0.1278568013827565],[0.07715563428078145,1.0003231050955415,-0.12863517442259056],[0.07586478988806297,1.0003262420382166,-0.12940067099996067],[0.07456635138180812,1.0003293789808918,-0.13015321448817435],[0.07326044873653416,1.000332515923567,-0.13089272955715167],[0.07194721267392323,1.0003356528662422,-0.13161914218096568],[0.07062677464973734,1.000338789808917,-0.13233237964525243],[0.06929926684065933,1.0003419267515923,-0.13303237055448983],[0.06796482213106199,1.0003450636942675,-0.13371904483914437],[0.06662357409970632,1.0003482006369426,-0.13439233376268506],[0.06527565700637,1.0003513375796178,-0.13505216992846408],[0.06392120577840821,1.000354474522293,-0.1356984872864631],[0.06256035599724698,1.0003576114649682,-0.13633122113990515],[0.061193243884811725,1.0003607484076433,-0.13695030815173054],[0.059820006289891044,1.0003638853503185,-0.13755568635093712],[0.05844078067443835,1.0003670222929937,-0.13814729513878363],[0.057055705099811574,1.0003701592356689,-0.13872507529485553],[0.055664918212953385,1.000373296178344,-0.1392889689829931],[0.054268559232512316,1.0003764331210192,-0.13983891975708088],[0.05286676793490712,1.0003795700636944,-0.1403748725666979],[0.051459684640334805,1.0003827070063693,-0.14089677376262838],[0.05004745019872475,1.0003858439490445,-0.14140457110223192],[0.04863020597563932,1.0003889808917197,-0.14189821375467307],[0.04720809383812328,1.0003921178343949,-0.14237765230600954],[0.04578125614050258,1.00039525477707,-0.14284283876413859],[0.04434983571013489,1.0003983917197452,-0.14329372656360098],[0.04291397583311217,1.0004015286624204,-0.14373027057024232],[0.04147382023991793,1.0004046656050956,-0.14415242708573092],[0.040029513091039554,1.0004078025477707,-0.14456015385193213],[0.03858119896253772,1.000410939490446,-0.14495341005513834],[0.03712902283157441,1.000414076433121,-0.14533215633015437],[0.03567313006190039,1.0004172133757963,-0.14569635476423812],[0.03421366638930443,1.0004203503184714,-0.14604596890089563],[0.032750777907024825,1.0004234872611466,-0.1463809637435303],[0.031284611051125594,1.0004266242038216,-0.1467013057589461],[0.029815312585837948,1.0004297611464967,-0.1470069628807043],[0.028343029588869265,1.000432898089172,-0.14729790451233338],[0.02686790943668034,1.000436035031847,-0.14757410153039166],[0.02539009978973311,1.0004391719745223,-0.1478355262873826],[0.02390974857770953,1.0004423089171974,-0.14808215261452243],[0.022427003984703955,1.0004454458598726,-0.14831395582435952],[0.020942014434389544,1.0004485828025478,-0.14853091271324573],[0.019454928575161252,1.000451719745223,-0.14873300156365893],[0.017965895265255764,1.0004548566878981,-0.14892020214637725],[0.016475063557850923,1.0004579936305733,-0.14909249572250366],[0.014982582686145178,1.0004611305732485,-0.14924986504534207],[0.013488602048419498,1.0004642675159237,-0.14939229436212356],[0.011993271193082255,1.0004674044585988,-0.14951976941558323],[0.010496739803699551,1.0004705414012738,-0.14963227744538754],[0.008999157684011713,1.000473678343949,-0.14972980718941134],[0.0075006747429377345,1.0004768152866241,-0.14981234888486547],[0.006001440979569533,1.0004799522292993,-0.14987989426927398],[0.004501606468156685,1.0004830891719745,-0.149932436581301],[0.003001321343084154,1.0004862261146497,-0.14996997056142788],[0.0015007357838434851,1.0004893630573248,-0.1499924924524794],[9.184850993605149e-18,1.0004925,-0.15],[-0.0015007357838435,1.0004956369426752,-0.1499924924524794],[-0.0030013213430841357,1.0004987738853504,-0.14996997056142788],[-0.0045016064681567,1.0005019108280255,-0.149932436
